### PR TITLE
Add trailing commas section to general convention

### PR DESCRIPTION
**Pull request by edgargressie**

### CODE REVIEW

**Comment by ns-rickvdmeij** [comment]
Hoewel het in Javascript mag, mag het niet in JSON. Dit kan problemen opleveren als er arrays en objecten 'geparsed' moeten worden. 

cannot parse
`const array = [1,2,3,];
JSON.parse(array); `

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas#Trailing_commas_in_JSON

**Comment by stevengunneweg** [comment]
@rickvandermeij-aanzee your array const isn't a valid JSON string anyway so parse will fail for sure. `JSON.stringify(array)` returns the expected result `"[1,2,3]"` but `JSON.parse("[1,2,3,]")` creates an error.
I think that this convention should be moved to the Javascript folder since, as far as I know, there are no other languages that support this behavior.

**Comment by edgargressie** [comment]
Please keep it in English guys. 🇺🇸  Maybe we can add a note to the array when JSON is needed. I think this is a global convention since you can have this option in other languages too. PHP for example.

> Having a trailing comma after the last defined array entry, while unusual, is a valid syntax.
— http://php.net/manual/en/function.array.php

**Comment by 7img** [comment]
JSON will either be a file that will be imported ( which will have a .json extension ), an HTTP JSON response or a string in your JS like so: 
```javascript
const jsonAsString = '{ "dummy": "true"}';
```
In this case a trailing comma would break the JSON.parse() because it isn't valid JSON. I don't really see a point in using this.

If you have static data you could add a .json file, import it and JSON.parse it or create a JS / TS object with the trailing comma's like so:

```javascript
const myStaticData = {
	static: 'data',
	boolean: true,
};
```
I prefer this format because allows more types than a JSON format would :)

**Comment by ns-rickvdmeij** [comment]
But since this request is a global convention, it does affect JSON files as well. So either it has to be declared in the description of the convention, that this excludes JSON files, or change it to language convention(s)

**Comment by 7img** [comment]
`+When possible, use trailing commas in arrays and objects.`

Maybe change this line to 

`+When its valid syntax, use trailing commas in arrays and objects.`

**Comment by edgargressie** [comment]
Thats why I added a description to this convention:

> When possible, use trailing commas in arrays and objects.

I think it's untenable to add all languages or situations. In JavaScript it depends on browsers and compile tools.

**Review by michaelmaat — APPROVED** [review]

**Comment by edgargressie** [comment]
I've updated the description

> Use trailing commas in arrays and objects when this is a valid syntax in your language.

**Review by ns-rickvdmeij — APPROVED** [review]

**Comment by stevengunneweg** [comment]
Trailing commas are not limited to arrays and objects. In TS for example you can have method parameters with trailing commas as well:
```
methodName(
    parameter1: string,
    parameter2: string,
    parameter3: string,
): void {
}
```

**Review by 7img — APPROVED** [review]
👍

**Comment by leondevries** [comment]
I don't agree, trailing comma's are wrong. For example coldfusion thinks the next element is empty.
Some languages tolerate trailing comma's but that doesn't make it right.

**Comment by ns-rickvdmeij** [comment]
I agree with Leon, the only reason i can imagine you want to use trailing comma is to have better a better git history, then maybe this is also a solution

```
const myStaticData = {
     static: 'data'
    ,boolean: true
};
```

then if you want to remove boolean, only a single line of code is touched.

**Comment by rsdebest** [comment]
@rickvandermeij-aanzee please don't.

**Comment by stevengunneweg** [comment]
@rickvandermeij-aanzee, I assume you meant the following?
```
const myStaticData = {
    static: 'data'
    ,boolean: true
};
```
That's a very ugly way of coding and it doesn't resolve the issue, just moved it to the first item instead of the last.

Since it seems to be very specific, my suggestion is to move this convention to appropriate languages specifically (JS, TS, PHP and other languages where this is allowed).

**Comment by edgargressie** [comment]
@leondevries I think your comment is wrong. As said before, in modern languages it's a valid syntax. We should strive for readability and scalability. If modern (versions of) languages provide better syntaxes we should embrace that. When it's impossible in your language, you can ignore this convention.

I still think that the current description `Use trailing commas in arrays and objects when this is a valid syntax in your language.` is clear enough. Use it when it's possible and valid.

**Comment by ns-rickvdmeij** [comment]
```
[1,].length --> 1
[1,2,].length --> 2
[].length --> 0 
[,].length --> 1    // <<<<=== valid?
```

the last array is valid according this convention

**Comment by 7img** [comment]
@rickvandermeij-aanzee the convention states that its a trailing comma. Trailing, generally, means behind something. That last array ugh... 🤢 

I have to agree with @edgargressie on this one. There are always cases where it isn't possible but we can't describe all the exceptions in this document. The **general** convention is that you use a trailing comma.

**Comment by ns-rickvdmeij** [comment]
@7img the `.length` on the last array implicates it has values in the array, so in theory it is an trailing comma. 
Nevertheless, if some syntax do support both trailing and non trailing, and others don't support trailing, I do prefer a single convention that covers all languages.

**Comment by 7img** [comment]
No value has been assigned so the 'value' is `undefined`. I think this is a whole other discussion though. The trailing comma is for when you assign a value and will most likely assign other values in the future.

I think the trailing comma's save time. I'm always duplicating lines when adding new values. This saves me some of the hassle of having to think about where and how many array / object values I'm going to add and where I have to strip or add comma's.

Wether or not to put this in the global conventions might be worth discussing some more. While searching for global / single conventions that cover all languages I couldn't really find any... This is the definition from WIkipedia for coding conventions:
> Coding conventions are a set of guidelines for a specific programming language that recommend programming style, practices, and methods for each aspect of a program written in that language. These conventions usually cover file organization, indentation, comments, declarations, statements, white space, naming conventions, programming practices, programming principles, programming rules of thumb, architectural best practices, etc. These are guidelines for software structural quality. Software programmers are highly recommended to follow these guidelines to help improve the readability of their source code and make software maintenance easier. Coding conventions are only applicable to the human maintainers and peer reviewers of a software project. Conventions may be formalized in a documented set of rules that an entire team or company follows, or may be as informal as the habitual coding practices of an individual. Coding conventions are not enforced by compilers.

**Comment by edgargressie** [comment]
Since this is a desired convention for all languages and a usable convention for some languages, I think that the global conventions is a good place. In combination with the added description it is clear enough.

I will update the convention with methods, import and export as mentioned by @stevengunneweg 👍 and research other cases.

**Review by stevengunneweg — APPROVED** [review]

**Pull request merged**
