### PR TITLE
Changed color conventions to HEX colors

### PR DESCRIPTION
**Pull request by romypetitjean**

### CODE REVIEW

**Review by bartvandebiezen — APPROVED** [review]
👍🏼

**Comment by edgargressie** [comment]
We also need to define how to use transparent colors. I prefer rgba which we already use in SCSS.

```
rgba(0, 0, 0, 0.5)
rgba($color-background, 0.5)
```

**Review by edgargressie — CHANGES_REQUESTED** [review]
We also need to define how to use transparent colors. I prefer rgba which we already use in SCSS.

```
rgba(0, 0, 0, 0.5)
rgba($color-background, 0.5)
```

**Comment by bartvandebiezen** [comment]
@edgargressie Added RGBA.

**Review by edgargressie — APPROVED** [review]

**Comment by edgargressie** [comment]
👍🏻

**Pull request merged**
